language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then composer remove "henrikbjorn/phpspec-code-coverage" --dev --no-update; composer remove "codeclimate/php-test-reporter" --dev --no-update; fi;'
  - composer install --prefer-source --no-interaction --dev

script:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then bin/phpspec run -v; else bin/phpspec run -v -c=phpspec.hhvm.yml; fi;'

after_script:
  - tests/travis_after_script.sh