language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - composer require illuminate/view:dev-master
  - composer require illuminate/events:dev-master
  - composer require illuminate/config:dev-master

script: bin/phpspec run -v

after_script:
  - bin/test-reporter --stdout > codeclimate.json
  - curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports